steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA", "."]

  - id: Push
    name: gcr.io/cloud-builders/docker
    args: ["push", "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"]

  - id: Migration
    name: gcr.io/cloud-builders/docker
    args: ["run", "-e", "DATABASE_URL=$$_DATABASE_URL", "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA", "--", "bundle", "exec", "rake", "ridgepole:apply"]
    secretEnv: ["_DATABASE_URL"]

  - id: Deploy
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '--project=${PROJECT_ID}'
      - '$_SERVICE_NAME'
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--set-secrets'
      - 'DATABASE_URL=projects/${PROJECT_ID}/secrets/DATABASE_URL/versions/latest,SECRET_KEY_BASE=projects/${PROJECT_ID}/secrets/SECRET_KEY_BASE/versions/latest'

substitutions:
  _LABELS: gcb-trigger-id=41ea1912-295d-426e-96f3-8d615de115e5
  _TRIGGER_ID: 41ea1912-295d-426e-96f3-8d615de115e5
  _PLATFORM: managed
  _SERVICE_NAME: tolymer-one-api
  _DEPLOY_REGION: asia-northeast1
  _GCR_HOSTNAME: asia.gcr.io
options:
  substitutionOption: ALLOW_LOOSE
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/DATABASE_URL/versions/latest
    env: _DATABASE_URL
images:
  - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - tolymer-one-api
