default: &default
  adapter: mysql2
  username: root
  password:
  host: 127.0.0.1
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tolymer_one_dev

test:
  <<: *default
  database: tolymer_one_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
